# Generated by Django 4.2.2 on 2023-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_user', models.CharField(max_length=100, verbose_name='Подписчик')),
                ('sub_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
        ),
    ]
