# Generated by Django 4.2.2 on 2023-08-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_sub_user_subscriber_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='user',
            new_name='subscriber',
        ),
    ]
