# Generated by Django 4.2.2 on 2023-08-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscriber_category_delete_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
