# Generated by Django 4.2.2 on 2023-08-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_post_options_alter_category_subscribers'),
        ('users', '0005_alter_subscriber_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='category',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='category',
            field=models.ManyToManyField(to='news.category'),
        ),
    ]
