# Generated by Django 4.2.2 on 2023-08-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subscriber_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
