# Generated by Django 4.2.2 on 2023-06-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoremPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCreation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=124)),
                ('text', models.TextField()),
            ],
        ),
    ]
