# Generated by Django 4.2.2 on 2023-07-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='category',
        ),
    ]
