# Generated by Django 4.2.3 on 2023-07-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_postcategory_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='postCategory',
        ),
    ]
