# Generated by Django 4.2.2 on 2023-08-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_subscriber_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
